FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Ordering.API/Ordering.API.csproj", "Ordering.API/"]
COPY ["src/Ordering.API.Application/Ordering.API.Application.csproj", "Ordering.API.Application/"]
COPY ["src/Ordering.API.Domain/Ordering.API.Domain.csproj", "Ordering.API.Domain/"]
COPY ["src/Ordering.API.Infrastructure/Ordering.API.Infrastructure.csproj", "Ordering.API.Infrastructure/"]
COPY ["src/Shared.Events/Shared.Events.csproj", "Shared.Events/"]
RUN dotnet restore "Ordering.API/Ordering.API.csproj"

COPY src/Ordering.API/ Ordering.API/
COPY src/Ordering.API.Application/ Ordering.API.Application/
COPY src/Ordering.API.Domain/ Ordering.API.Domain/
COPY src/Ordering.API.Infrastructure/ Ordering.API.Infrastructure/
COPY src/Shared.Events/ Shared.Events/
WORKDIR /src/Ordering.API
RUN dotnet publish "Ordering.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Ordering.API.dll"]
