FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["src/FastFoodSystem.Gateway/FastFoodSystem.Gateway.csproj", "FastFoodSystem.Gateway/"]

RUN dotnet restore "FastFoodSystem.Gateway/FastFoodSystem.Gateway.csproj"

COPY ["src/FastFoodSystem.Gateway/", "FastFoodSystem.Gateway/"]

WORKDIR "/src/FastFoodSystem.Gateway"

RUN dotnet build "FastFoodSystem.Gateway.csproj" -c Release -o /app/build

RUN dotnet publish "FastFoodSystem.Gateway.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FastFoodSystem.Gateway.dll"]
